### DISCUSSION TITLE
Which command with multiple matching globs?

### DISCUSSION THREAD

**Discussion by tomdavidson** [remirror/remirror#1947] [Q&A]
Hello, I could use some clarification on matching. I have two commands with parallel=true. Is a file only passed to the first match or is it provided to all matching commands?

This config is produces inconsistent behavior. Excluded files are still processed by prettier. Some times dprint gets a file sometimes not.

```yaml
pre-commit:
  parallel: true
  commands:
    dprint:
      glob: '**/*.*'
      run: dprint fmt -- {staged_files} || pnpx dprint fmt -- {staged_files}
    prettier:
      glob: '**/*.*'
      exclude: '**/*.{ts,tsx,cjs,js,jsx,mjs,json,md}|!package.json'
      run: 'prettier --write --cache --config configs/prettier-config/prettier-config.json {staged_files}'
```
