### ISSUE TITLE
Create a `release` workflow

### ISSUE THREAD

**Issue by ifiokjr** [remirror/remirror#474]
### Description

Move the releases from the current `.github/workflows/ci.yml` into a file and let it be triggered on [`workflow_run`](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_run) events when all the tests have passed for the latest push.

Something like this should do the trick.

```yaml
on:
  workflow_run:
    workflows: ["Node CI"]
    branches: [main, next]
    types: 
      - completed
```

The action should then respond collect the release information from the workflow run and create the release from the received data. 

This depends on #497 since the action used will be the same.
