### ISSUE TITLE
Improve CSS

### ISSUE THREAD

**Issue by ifiokjr** [remirror/remirror#696]
### Description

There are currently a few issues with styles caused by the `precss` package. For example, the following, which is invalid, is produced when generating the css.

```css
.remirror-editor {
  @-webkit-keyframes ProseMirror-cursor-blink {
    to {
      visibility: hidden;
    }
  }
}
```

Additionally the way the styles are created for `styled-components` and `emotion` are not ideal. The components should just reuse the `css` exports rather than redefining everything. Also the TypeScript types are broken at the moment.

- [ ] Upgrade `autoprefixer` and `postcss`
- [ ] Replace `precss` with just `postcss-nested`
- [ ] Fix core styles for `@remirror/styles/styled-components`, `@remirror/styles/emotion` and `@remirror/styles/dom`.
- [ ] Add a css clean command to delete all css and regenerate from scratch.
